### ISSUE TITLE
endTurn does not show new controls

### ISSUE THREAD

**Issue by vashti123** [csmith1188/JSFighter-Class-#35]
`// EndTurn code
function endTurn() {
  playerTurn = !playerTurn
  if (koCheck(Player0, 0) || koCheck(Player1, 0)){
    hideControls();
  }
}`
We need an else statement that runs show controls.

**Comment by Gsimons2002** [comment]
put 


else{
showControls();
}

**Comment by csmith1188** [comment]
Resolved by #44
