### ISSUE TITLE
Bars Broken (again)

### ISSUE THREAD

**Issue by sfetrow** [csmith1188/JSFighter-Class-#78]
Someone didn't update their code so its back to being red instead of green/blue.

**Comment by csmith1188** [comment]
I checked it out and it works for me. Make sure you have your RC selected and not your working branch? Also check to see if your RC's code matches what is in this repo's RC now.

![Capture](https://user-images.githubusercontent.com/56306641/69473953-689c2b80-0d88-11ea-9e18-276f1fa926e6.PNG)
